### ISSUE TITLE
MangoPay Vault IOS installation issue in Flutter project

### ISSUE THREAD

**Issue by JIGSIG** [Mangopay/mangopay-ios-vault-sdk#9]
Hello, i'm try to install mangopay vault IOS sdk using the CocoaPod installation method (https://mangopay.com/docs/sdk/vault-ios).
But I have the following error when I try the `pod install`:

> [!] An unexpected version directory `Networking` was encountered for the `/Users/myUser/.cocoapods/repos/mangopay-mangopay-ios-vault-sdk/MangopayVault` Pod in the `MangopayVault` repository.

how to I fix it ?

**Comment by jidefela-mgp** [comment]
Hello @JIGSIG, We will try to reproduce the issue on our end and get back to you momentarily

**Comment by elviva-mgp** [comment]
Hi @JIGSIG, this has been resolved now please.
Kindly use `pod MangopayVaultSDK` in your pods instead of `pod MangopayVault`.
The documentation has been updated accordingly. 
Apologies for the inconvenience.

**Comment by aggeloskoutanis** [comment]
I am still getting this error despite using  `pod 'MangopayVaultSDK'`
